version: '0.1-{build}'

image: Visual Studio 2017
platform: x64
test: off

configuration: release

branches:
  only:
  - master
skip_branch_with_pr: true

init:
  - cmd: git config --global lfs.fetchexclude "*"

before_build:
  - cmd: git submodule update --init --recursive
  - ps: Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-windows.zip' 'premake.zip'
    # Extract it in-place; premake5.exe is at the top level.
  - 7z x premake.zip
  - cmd: premake5 vs2017

build:
  parallel: true
  project: build/RenderBackend.sln

install:
 - set COMMIT_SHA=%APPVEYOR_REPO_COMMIT:~0,8%

artifacts:
 - path: lib
   name: 'renderbackend-v0.1-$(COMMIT_SHA)_win64'
   type: zip